import type { Metadata } from "next";
import "./globals.css";
import { fraunes, inter } from "./font";
import { cn } from "@/lib/utils";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                suppressHydrationWarning
                className={cn(
                    "antialiased",
                    fraunes.className,
                    inter.className
                )}
            >
                {children}
            </body>
        </html>
    );
}
